### disable caching
POST http://localhost:8100/tinyUrl/command/_create
Content-Type: application/json

{
  "url": "http://192.168.0.192:9900/2023-07/25-1690271629042-AeO.xls"
}


### using cache
POST http://localhost:8100/tinyUrl/command/_create
Content-Type: application/json

{
  "url": "https://www.baidu.com",
  "enableCache": true
}

### using maxCount
POST http://localhost:8100/tinyUrl/command/_create/limitAccessCount
Content-Type: application/json

{
  "url": "https://www.baidu.com",
  "maxCount": 2,
  "enableCache": true
}


### request with tiny url
GET http://localhost:8100/s/eqXK0W5zlj6
