spring:
  application:
    name: tiny-url
  profiles:
    active: @profiles.active@
#  cloud:
#    nacos:
#      discovery:
#        server-addr: @nacos.url@
#        namespace: public
#      config:
#        server-addr: @nacos.url@
#        namespace: public
#        group: DEFAULT_GROUP
#        fileExtension: yaml
